@APIproject_HostAddress = https://localhost:44392
@item_id=3
// endpoints for item controller
GET {{APIproject_HostAddress}}/item/item
Accept: application/json

###

GET {{APIproject_HostAddress}}/item/item/{{item_id}}
accept: application/json

###

POST {{APIproject_HostAddress}}/item/item  
Content-Type: application/json
{
  "name": "abrar",
  "description": "abrar saleem"
}
###

PUT {{APIproject_HostAddress}}/item/item/{{item_id}}
Accept: application/json
Content-Type: application/json
{  "id":4,
  "name": "aqib",
  "description": "aqib arshad"
}

###
DELETE {{APIproject_HostAddress}}/item/item/{{item_id}}
Accept: application/json

 ###
 
// endpoints for order controller

@order_id=2

GET {{APIproject_HostAddress}}/order/order
Accept: application/json

###



GET {{APIproject_HostAddress}}/order/order/{{order_id}}

###



POST {{APIproject_HostAddress}}/order/order
Content-Type: application/json


 {
  "order_id": 0,
  "order_name": "string",
  "order_details": "string"
}


###


PUT {{APIproject_HostAddress}}/order/order/{{order_id}}
Content-Type: application/json

{
  "order_id": {{order_id}},
  "order_name": "samosa",
  "order_details": "chicken samosa"
}

###

  

DELETE {{APIproject_HostAddress}}/order/order/{{order_id}}

###
