@APIproject_HostAddress = https://localhost:44392
@item_id=3
// endpoints for item controller
GET {{APIproject_HostAddress}}/item/Item
Accept: application/json

###

GET {{APIproject_HostAddress}}/item/Item/{{item_id}}
accept: application/json

###

POST {{APIproject_HostAddress}}/item/Item  
Content-Type: application/json
{
  "name": "Table",
  "description": "Brown Table"
}
###

PUT {{APIproject_HostAddress}}/item/Item/{{item_id}}
Accept: application/json
Content-Type: application/json
{  "id":3,
  "name": "Desk",
  "description": "Large Size"
}

###
DELETE {{APIproject_HostAddress}}/item/Item/{{item_id}}
Accept: application/json

 ###
 
// endpoints for order controller

@order_id=2

GET {{APIproject_HostAddress}}/order/Order
Accept: application/json

###



GET {{APIproject_HostAddress}}/order/Order/{{order_id}}

###



POST {{APIproject_HostAddress}}/order/Order
Content-Type: application/json


 {
  "order_name": "chicken",
  "order_details": "leg piece"
}


###


PUT {{APIproject_HostAddress}}/order/Order/{{order_id}}
Content-Type: application/json

{
  "order_id": {{order_id}},
  "order_name": "samosa",
  "order_details": "chicken samosa"
}

###

  

DELETE {{APIproject_HostAddress}}/order/Order/{{order_id}}

###
